### ISSUE TITLE
Windows 10 Video Adapter Ram reports zero bytes

### ISSUE THREAD

**Issue by jon-stumpf** [vrozenfe/qxl-dod#10]
In trying to debug a problem with an application, I noticed that the Video Adapter RAM reported by the driver is zero (0) bytes.  I suspect this is contributing to my graphics application error that checks the configuration of my box before starting.

My XML configuration is the following:
```
<video>
      <model type='qxl' ram='131072' vram='131072' vgamem='524288' heads='1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
</video>
```
And, the resulting qemu call has the following argument (newlines added):
```
-device qxl-vga,
        id=video0,
        ram_size=134217728,
        vram_size=134217728,
        vgamem_mb=512,
        bus=pci.0,
        addr=0x2 
```
I have attached a screenshot of the driver information from msinfo32.
![screenshot-17](https://user-images.githubusercontent.com/7144996/38165833-e2e20be2-34e7-11e8-8481-a6fbd4f91814.png)

I am running:
- c:\windows\system32\drivers\qxldod.sys (10.0.0.18000, 59.27 KB (60,696 bytes), 1/1/2018 8:23 PM)
- Windows 10 Pro, Build 16299 (Version 10.0.16299)
- QEMU emulator version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.24)

Is this a bug?  Do I have a configuration issue?

**Comment by vrozenfe** [comment]
Hi Jon,

I believe this is the driver's problem. 0 size must be coming from the following code in QxlDod.cpp: 

    RtlInitUnicodeString(&ValueNameMemorySize, L"HardwareInformation.MemorySize");
    DWORD MemorySize = 0; // BDD has no access to video memory
    Status = ZwSetValueKey(DevInstRegKeyHandle,
                           &ValueNameMemorySize,
                           0,
                           REG_DWORD,
                           &MemorySize,
                           sizeof(MemorySize));
    if (!NT_SUCCESS(Status))
    {
        DbgPrint(TRACE_LEVEL_ERROR, ("ZwSetValueKey for MemorySize failed with Status: 0x%X\n", Status));
        return Status
    }
 
There is some information about how WDDM driver reports graphic memory 
https://docs.microsoft.com/en-us/windows-hardware/drivers/display/examples-of-graphics-memory-reporting.

Best,
Vadim.

**Comment by jon-stumpf** [comment]
I have reviewed the references that you provided: the code (_permalink_ below) and the graphics memory reporting reference from the Microsoft WDDM documentation.  Thank you.

My continued investigation suggests that Windows has the memory allocated appropriately (i.e., as I had configured the VM, see _System Information - Memory_ below).  I verified the registry information for the driver (see _Registry Information_ below).  When using **ZwSetValueKey()** as the driver does, I found a [reference](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/registering-hardware-information) in the Microsoft documentation that the units for **HardwareInformation.MemorySize** is in megabytes.  However, changing the registry key requires the value to be in bytes (e.g., 512MB is 0x20000000, not 0x200); see _System Information - Adapter RAM_ below.  Most likely, the documentation means that the value must be in whole megabytes.

I don't understand the comment on line 1966 regarding the Basic Display Driver (BDD) not having access to video memory.
https://github.com/vrozenfe/qxl-dod/blob/dd8fc1a4520006f648ea9ec02bc646eda392cbee/qxldod/QxlDod.cpp#L1966
The documentation for [DxgkcbGetDeviceInformation](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/dispmprt/nc-dispmprt-dxgkcb_get_device_information) suggests that you have access to this information in the [DXGK_DEVICE_INFO](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/dispmprt/ns-dispmprt-_dxgk_device_info) type, in **SystemMemorySize**.

Given the above, my questions are:

1. Why does the driver not acquire the Video RAM size from the virtual machine?
2. When you say that you "believe this is the driver's problem," do you mean that the call to ZwSetValueKey() is incorrect (i.e., this is a bug that you will address)?
3. Why do you not use [**VideoPortSetRegistryParameters()**](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/video/nf-video-videoportsetregistryparameters) function?
4. Lastly, can someone provide descriptions for each of the **QXL command line options** in the [SPICE](https://www.spice-space.org/spice-user-manual.html) documentation?

Thanks.

# **References**
## **Permalink**
https://github.com/vrozenfe/qxl-dod/blob/dd8fc1a4520006f648ea9ec02bc646eda392cbee/qxldod/QxlDod.cpp#L1963-L1977

## **System Information - Memory**
![image](https://user-images.githubusercontent.com/7144996/38472037-c20fe978-3b47-11e8-8cac-1fd936a36607.png)

## **Registry Information**
![image](https://user-images.githubusercontent.com/7144996/38472737-6f493ab8-3b52-11e8-9693-272e4b86c62e.png)

## **System Information - Adapter RAM** (after the registry modification)
![image](https://user-images.githubusercontent.com/7144996/38472756-db993402-3b52-11e8-8cda-9ba80a12cb81.png)

**Comment by vrozenfe** [comment]
Hi Jon,
First of all thank you the update and sharing your findings.

I would suggest you to open a thread at spice-devel (spice-devel@lists.freedesktop.org) list to discuss
all issues. You should also switch to https://gitlab.com/spice/qxl-wddm-dod.git repository and rebase you patches against the most recent code from this repo. 

I was the original developer of qxl-dod driver but I don't own it any more. Spice team handles and resolves all driver related issues, from the moment when driver was accepted for production. 

Regarding to BDD comment, qxl-dod driver was build on top of KM DOD sample provided by Microsoft, 
so it is the reason why you can see some irrelevant code leftovers or strange comments from time to time when walking through the qxl-dod driver code.

Best regards,
Vadim.

**Comment by jon-stumpf** [comment]
Thanks.

**Comment by jon-stumpf** [comment]
Vadim,

Is anyone working on the Spice qxl-dod driver?  You are not working on this and responded in 3 days.  I haven't heard anything for a week at the Spice gitlab repo.

- jss

**Comment by vrozenfe** [comment]
I will ask guys, who supposed to be qxl-dod maintainers, to take a look at this. 

Best,
Vadim.

**Comment by vrozenfe** [comment]
Hi Jon,

Please ping me offline (vrozenfe [at] redhat.com), and I will connect you with the right people.

Best,
Vadim.

**Comment by jon-stumpf** [comment]
Thanks.

**Comment by geekette86** [comment]
Any result on this when i change the register key and reboot , i get agian a 0 for memory
