### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by batonac** [vrozenfe/qxl-dod#2]
I'd really like to experiment with this driver for performance testing.  Currently, the drivers from http://people.redhat.com/~vrozenfe/qxlwddm/ cause a BSOD on Windows 7.  I know that weren't built for that platform, would this be a possibility in future builds?

**Comment by vrozenfe** [comment]
Unfortunately, there is no plan to provide support for Windows 7.

**Comment by batonac** [comment]
Very well...

Thanks for your work
