### ISSUE TITLE
Custom resolution support?

### ISSUE THREAD

**Issue by sonicflare** [vrozenfe/qxl-dod#3]
I have no idea what is the correct place to ask and what piece from SPICE mess does handle resolution, but anyway. 
In the spice documentation there is described ability to adjust vm resolution to host spice client window size, however, this have not worked at all, ever.  (Even on Windows 7 VMs)
So hence the question, is there a way to actually force a custom resolution? I'm up for any ways (console command with magic numbers, magic numbers + device guid's in registry, you name it)

**Comment by vrozenfe** [comment]
For SPICE related question you can try asking spice developers at spice-devel list - http://lists.freedesktop.org/mailman/listinfo/spice-devel
From my own experience - arbitrary resolutions feature works flawlessly on Windows 7.
Do you have virtio-serial device driver and vdagent service installed and running on your system?

**Comment by sonicflare** [comment]
Hm, I tired with spicy and it does adjust it, but only to resolutions that are available by Change Resolution screen, and not really making custom resolution with the size of the window.

**Comment by vrozenfe** [comment]
Win7 or 8 ? Can you confirm that vdagent is up and running on your system?

**Comment by sonicflare** [comment]
Server 2012 r2, effectivly its win8. Spicy in status bar is telling: Cursor: Server, Agent: yes

**Comment by vrozenfe** [comment]
Probably not yet supported by vdagent. For more information please visit the following link - https://bugzilla.redhat.com/show_bug.cgi?id=895356#c93

**Comment by sonicflare** [comment]
Thanks for clarification!
