### ISSUE TITLE
Poor 2D performance on Windows 10

### ISSUE THREAD

**Issue by dragetd** [vrozenfe/qxl-dod#6]
Running this driver on Windows 10 gives poor 2D performance. The cursor stutters and working with the system generally feels very sluggish. If I am not mistaken, using the old drivers will not work with Windows10 anymore. So there are not real alternatives to this drive, or?

**Comment by mandumeans** [comment]
I totally agree on this. When I played a 1080p video on Windows 10, It was too slow to do other job. I tried to rebuild qxl driver from this repository. But it didn't work out either. I found spice-server's network traffic had gone really high(compare to Windows 7). Is it related to this issue?

**Comment by vrozenfe** [comment]
qxl-dod is a Display Only Driver, which technically is a frame-buffer driver, without any notion about 3D/2D acceleration  (unlike XDDM-style qxl driver designed to work on WinXP..Win7 platforms).

**Comment by mandumeans** [comment]
Thanks for response. We keep researching this subject for 2 weeks. I want to clarify just one thing. Is there any way that you know to accelerate 3D/2D performance on Windows 10?

**Comment by vrozenfe** [comment]
Unfortunately, there is no way to get accelerated 3D/2D performance with DOD-style driver, because it always  works with software-based 3D/2D rendering. The current driver needs to be converted/extended  to Full Graphics or Render Only driver to show more or less advanced performance.

**Comment by saivert** [comment]
I believe the mouse cursor lag is unrelated to the 2D performance as it is just as slow with the Microsoft Basic Display driver. This might be because it isn't using a hardware cursor but one that is rendered as part of the composited desktop (or software cursor if you want).

qxldod has no tearing unlike Microsoft Basic Display driver so it is an improvement overall.

**Comment by dragetd** [comment]
The sluggish graphics performance and lack of guest-auto-resizing are a real show stopper for Win10 guests for regular desktop usage. Guess I have to switch back to Windows7 as a guest then.

**Comment by saivert** [comment]
Very little point in improving qxldod when virtual GL is around the corner. Also for better 2D just use RDP. RDP beats even the qxl driver for Window 7 in responsiveness. A new driver will have to be written to take advantage of the virgl capability in QEMU.

**Comment by dragetd** [comment]
I will keep an eye on the virtual GL progress. Thanks for the input!
