### ISSUE TITLE
Custom resolution on Windows 10

### ISSUE THREAD

**Issue by leth** [vrozenfe/qxl-dod#7]
Hi, is custom resolution supported on Windows 10? The display size seems to stick to fixed aspect ratios when using remote-viewer.
I just upgraded my VM from Windows 7, where it worked perfectly.

**Comment by vrozenfe** [comment]
This project is handled by spice team now.
(https://gitlab.com/spice/qxl-wddm-dod/commits/master)

AFAIK the custom resolutions should work on Windows 10, but this feature requires the most recent spice agent to be installed . Please see https://bugzilla.redhat.com/show_bug.cgi?id=895356#c166 for more information.

Best regards,
Vadim.

**Comment by leth** [comment]
Ah thanks; I found this repo and your releases by googling. Perhaps you could update the repo description & readme to point to the new repo!
